---
hero_image: images/banner.png
theme: turquoise
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Uhvati točke
description: U ovom projektu naučit ćeš kako kreirati igru u kojoj moraš uskladiti obojane točke s dijelovima kontrolera.
original_url: https://codeclubprojects.org/en-GB/scratch/catch-the-dots
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Uhvati točke