---
hero_image: images/banner.png
theme: turquoise
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Dal dotiau
description: Dysga sut i greu gêm i ddal dotiau.
original_url: https://codeclubprojects.org/en-GB/scratch/catch-the-dots
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Cyflwyniad
- title: Creu rheolwr
- title: "Her: Troi i'r chwith"
- title: Casglu dotiau
- title: 'Her: Mwy o ddotiau'
- title: Gwneud y gêm yn anoddach
- title: 'Her: Dotiau yn symud yn gynt'
- title: Sgôr uchel
- title: 'Her: Gwella dy gêm!'
- title: 'Her: Dewislen y gêm'