---
hero_image: images/banner.png
theme: turquoise
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Attrapes les points
description: Apprends à programmer un jeu où il faut attraper des points.
original_url: https://codeclubprojects.org/en-GB/scratch/catch-the-dots
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: "Création d'un contrôleur"
- title: 'Défi : Tourner à gauche'
- title: Rassemblement de points
- title: 'Défi : Plus de points'
- title: Augmentation de la difficulté
- title: 'Défi : Points plus rapides'
- title: Meilleur score
- title: 'Défi : Améliorez votre jeu!'